<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.epam.ftm.selenium.part2.firefox.NewTest2" tests="7" time="30.681" ignored="0" failures="1" timestamp="06 Nov 2017 17:07:52 GMT" skipped="0" hostname="Tatsianas-MacBook-Air.local" errors="0">
  <testcase name="loginToMailRu" time="12.566" classname="com.epam.ftm.selenium.part2.firefox.NewTest2"/>
  <testcase name="createLetter" time="10.474" classname="com.epam.ftm.selenium.part2.firefox.NewTest2"/>
  <testcase name="verifyContent" time="2.638" classname="com.epam.ftm.selenium.part2.firefox.NewTest2">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
	at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:49)
	at com.epam.ftm.selenium.part2.firefox.NewTest2.verifyContent(NewTest2.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyContent -->
  <testcase name="draftExist" time="1.033" classname="com.epam.ftm.selenium.part2.firefox.NewTest2"/>
  <testcase name="signOut" time="3.100" classname="com.epam.ftm.selenium.part2.firefox.NewTest2"/>
  <testcase name="saveDraft" time="0.736" classname="com.epam.ftm.selenium.part2.firefox.NewTest2"/>
  <testcase name="verifyMessageSent" time="0.134" classname="com.epam.ftm.selenium.part2.firefox.NewTest2"/>
</testsuite> <!-- com.epam.ftm.selenium.part2.firefox.NewTest2 -->
